[package]
name = "snowmaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pervasives = { git = "https://github.com/rajatsharma/pervasives", version = "0.1.0" }
